run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - unused        # Check for unused code
    - gofmt         # Format code
    - goimports     # Manage imports
    - misspell      # Find misspellings
    - gocritic      # Opinionated linter
    - revive        # Fast, extensible linter
    - gosec         # Security checks
    - unconvert     # Remove unnecessary type conversions
    - prealloc      # Find slice declarations that could be preallocated
    - exportloopref # Check for pointers to loop variables

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true

  govet:
    enable-all: true

  gofmt:
    simplify: true

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style

  revive:
    confidence: 0.8

  gosec:
    excludes:
      - G404 # Use of weak random number generator (math/rand instead of crypto/rand)

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
